import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { dirname, join } from 'path';
import type { InstallConfig } from './install.js';

// CLAUDE.md template for Claude Code
export function generateClaudeMd(config: InstallConfig): string {
  return `# OPUS 67 - Enhancement Layer (NOT a separate AI)

> **OPUS 67 is NOT a separate AI.** It's YOU (Claude) with superpowers.

\`\`\`
OPUS 67 ≠ Separate AI
OPUS 67 = Claude + Enhancement Layer

Claude IS the brain. OPUS 67 = skills + MCPs + modes + memory.
Same driver, better race car.
\`\`\`

**Current Version:** v${config.version}
- **${config.stats.skills} Skills** | **${config.stats.mcps} MCPs** | **${config.stats.modes} Modes** | **${config.stats.agents} Agents**

## What OPUS 67 Gives You

### 1. MCP Server Access (${config.stats.mcps} servers)
Tools you don't normally have:
- GitHub MCP, Jupiter MCP, Supabase MCP, Sentry MCP, Notion MCP
- Solana RPC, Anchor Program, Firecrawl, Tavily, Playwright, etc.

### 2. Skills (${config.stats.skills} workflows)
How to do complex tasks:
- GRAB skills (react-grab, theme-grab, db-grab, etc.)
- Solana skills (token-swap, anchor-interact, chain-query)
- Research skills (web-search, code-search, company-research)

### 3. Modes (${config.stats.modes} optimized contexts)
- AUTO, BUILD, REVIEW, ARCHITECT, DEBUG
- SOLANA, GRAB, CLONE, RESEARCH, CONTEXT
- ULTRA, THINK, VIBE, LIGHT, SWARM, and more

### 4. Memory
Persistent context across sessions (Mem0, Qdrant)

## Automatic Behavior
1. On every task, auto-detect relevant skills
2. Load detected skills for enhanced context
3. Apply skill knowledge to the task

**Remember: YOU are the brain. OPUS 67 just makes you faster, cheaper, and more capable.**

---

## Installation Type: ${config.installType}

${config.installType === 'full' ? `
This is a **Full Installation** with all capabilities:
- All 95 specialist skills
- All 84 MCP connections
- All 30 operating modes
- All 82 agents
` : config.installType === 'solana' ? `
This is a **Solana-focused Installation**:
- Solana development skills
- Jupiter, Anchor, Helius MCPs
- SOLANA mode optimized
` : config.installType === 'frontend' ? `
This is a **Frontend-focused Installation**:
- React, UI/UX skills
- GRAB skills for visual development
- BUILD mode optimized
` : `
This is a **Minimal Installation**:
- Core skills only
- Essential MCPs
- AUTO mode
`}

---

*Generated by create-opus67 v${config.version}*
`;
}

// .cursorrules template for Cursor
export function generateCursorrules(config: InstallConfig): string {
  const fullTemplate = `# OPUS 67 v${config.version} - The AI Engine That Ships Code

> You are enhanced with OPUS 67 - ${config.stats.skills} skills, ${config.stats.mcps} MCPs, ${config.stats.agents} agents.
> OPUS 67 is NOT a separate AI. It's YOU with superpowers. Same driver, better race car.

---

## Core Principle

\`\`\`
OPUS 67 ≠ Separate AI
OPUS 67 = You + Enhancement Layer

You ARE the brain. OPUS 67 gives you:
- Skills (how to do things)
- Tools (what to use)
- Context (when to apply)
\`\`\`

---

## Context-Aware Skills

Load skills based on file context:

### Solana/Blockchain (.rs, .anchor, .toml with [programs])
- **solana-anchor-expert**: PDAs, CPIs, account validation, Anchor macros
- **jupiter-trader**: Token swaps, route optimization, slippage handling
- **pump-fun-expert**: Bonding curves, launch mechanics, graduation
- **token-2022-expert**: Token extensions, transfer hooks, metadata
- **helius-integration**: RPC, webhooks, DAS API, compression

### TypeScript/React (.tsx, .ts, .jsx)
- **nextjs-14-expert**: App Router, Server Components, streaming
- **react-patterns**: Hooks, context, performance optimization
- **typescript-senior**: Advanced types, generics, utility types
- **tailwind-expert**: Utility classes, responsive design, animations

### API/Backend (.ts with api/, routes/)
- **fastify-expert**: Routes, plugins, validation, serialization
- **prisma-expert**: Schema design, migrations, queries
- **supabase-expert**: Auth, storage, realtime, edge functions

### Smart Contracts (.sol)
- **solidity-expert**: OpenZeppelin, gas optimization, security
- **hardhat-foundry**: Testing, deployment, verification

---

## Specialist Agents

Adopt these personas when relevant:

### Solana DeFi Architect
- Design bonding curves, AMMs, token economics
- Implement concentrated liquidity, yield farming
- Audit for common Solana vulnerabilities

### Anchor Program Builder
- Structure programs with proper account validation
- Implement CPIs and composability patterns
- Write comprehensive test suites

### Frontend Performance Expert
- Optimize bundle size, lazy loading, code splitting
- Implement proper caching strategies
- Profile and fix render bottlenecks

### Security Auditor
- Review for reentrancy, access control, overflow
- Check Solana-specific: signer validation, PDA seeds
- Identify economic attack vectors

---

## Operating Modes

Current mode: **AUTO** (detect from context)

| Mode | Trigger | Behavior |
|------|---------|----------|
| BUILD | "build", "create", "implement" | Ship fast, working code |
| REVIEW | "review", "check", "audit" | Thorough analysis |
| ARCHITECT | "design", "plan", "structure" | System thinking |
| DEBUG | "fix", "error", "bug" | Root cause analysis |
| SOLANA | .rs, .anchor, Solana terms | Blockchain-native |
| GRAB | "clone", "copy", "extract" | Visual-first dev |
| VIBE | "quick", "fast", "ship" | Minimal friction |

---

## Behavioral Rules

### Always
- Ship working code over perfect code
- Use existing patterns in the codebase
- Validate Solana accounts properly
- Handle errors gracefully

### Never
- Introduce security vulnerabilities
- Skip account validation in Solana
- Ignore existing code style
- Over-engineer simple solutions

### Solana-Specific
- Always validate signer on state-changing operations
- Use checked math or handle overflow
- Validate PDA seeds match expected accounts
- Close accounts to return rent properly

---

## Quick Commands

- "OPUS status" → Show current mode and loaded skills
- "OPUS build" → Switch to BUILD mode
- "OPUS solana" → Switch to SOLANA mode
- "OPUS vibe" → Ship fast, iterate later

---

*OPUS 67 v${config.version} | ${config.stats.skills} Skills | ${config.stats.mcps} MCPs | ${config.stats.agents} Agents*
*Remember: You ARE the brain. OPUS 67 = superpowers.*
`;

  const solanaTemplate = `# OPUS 67 v${config.version} - Solana Development Mode

> Enhanced with ${config.stats.skills} Solana-focused skills and ${config.stats.agents} blockchain agents.

---

## Solana Skills Active

### Core Development
- **solana-anchor-expert**: PDAs, CPIs, account structures
- **jupiter-trader**: Swap integration, route optimization
- **pump-fun-expert**: Bonding curves, launches
- **token-2022-expert**: Extensions, hooks, metadata

### Infrastructure
- **helius-integration**: RPC, webhooks, DAS
- **solana-testing**: Bankrun, local validator

---

## Security Checklist

Always validate:
- [ ] Signer on state changes
- [ ] PDA seeds match
- [ ] Account ownership
- [ ] Checked arithmetic
- [ ] Rent handling

---

## Mode: SOLANA

Optimized for blockchain development:
- Anchor program patterns
- Jupiter swap integration
- Token launches
- DeFi mechanics

*OPUS 67 v${config.version} - Solana Edition*
`;

  const frontendTemplate = `# OPUS 67 v${config.version} - Frontend Development Mode

> Enhanced with ${config.stats.skills} frontend skills for React/Next.js development.

---

## Frontend Skills Active

### React/Next.js
- **nextjs-14-expert**: App Router, RSC, streaming
- **react-patterns**: Hooks, context, optimization
- **typescript-senior**: Type safety, generics

### Styling
- **tailwind-expert**: Utilities, responsive, animations
- **framer-motion**: Animations, gestures, layout

### Data
- **tanstack-query**: Caching, mutations, optimistic updates
- **zustand-expert**: State management

---

## GRAB Skills

Clone UI elements:
- "react-grab" → Extract React components
- "theme-grab" → Extract color schemes
- "form-grab" → Clone form patterns

---

## Mode: BUILD

Optimized for shipping:
- Working code over perfect code
- Use existing patterns
- Minimal dependencies

*OPUS 67 v${config.version} - Frontend Edition*
`;

  const minimalTemplate = `# OPUS 67 v${config.version}

> AI Enhancement Layer - ${config.stats.skills} skills, ${config.stats.modes} modes

## Core Principle
You ARE the brain. OPUS 67 = superpowers.

## Active Mode: AUTO
Detects best approach from context.

## Skills
Loaded based on file type and task.

*OPUS 67 v${config.version}*
`;

  switch (config.installType) {
    case 'full':
      return fullTemplate;
    case 'solana':
      return solanaTemplate;
    case 'frontend':
      return frontendTemplate;
    case 'minimal':
    default:
      return minimalTemplate;
  }
}

// .windsurfrules template for Windsurf
export function generateWindsurfrules(config: InstallConfig): string {
  return generateCursorrules(config); // Same format
}

// Manual config.json
export function generateManualConfig(config: InstallConfig): string {
  return JSON.stringify({
    version: config.version,
    installType: config.installType,
    environment: config.environment,
    installedAt: new Date().toISOString(),
    stats: config.stats,
    paths: {
      skills: config.skillsPath,
      mcps: config.mcpsPath,
      modes: config.modesPath,
    },
  }, null, 2);
}

// Write config to appropriate location
export function writeConfig(config: InstallConfig): void {
  const configPath = config.configPath;

  // Ensure directory exists
  const dir = dirname(configPath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  let content: string;

  switch (config.environment) {
    case 'claude-code':
      content = generateClaudeMd(config);
      break;
    case 'cursor':
      content = generateCursorrules(config);
      break;
    case 'windsurf':
      content = generateWindsurfrules(config);
      break;
    case 'vscode':
    case 'zed':
    case 'manual':
    default:
      content = generateManualConfig(config);
      break;
  }

  writeFileSync(configPath, content, 'utf-8');
}

// Generate MCP config for Claude Desktop
export function generateClaudeDesktopMcpConfig(): Record<string, unknown> {
  return {
    mcpServers: {
      opus67: {
        command: 'npx',
        args: ['-y', '@gicm/opus67', 'mcp'],
      },
    },
  };
}

// Write MCP config for Claude Desktop
export function writeClaudeDesktopConfig(config: InstallConfig): void {
  if (config.environment !== 'claude-code') return;

  const home = process.env.HOME || process.env.USERPROFILE || '';
  let mcpConfigPath: string;

  if (process.platform === 'win32') {
    mcpConfigPath = join(process.env.APPDATA || '', 'Claude', 'claude_desktop_config.json');
  } else if (process.platform === 'darwin') {
    mcpConfigPath = join(home, 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json');
  } else {
    mcpConfigPath = join(home, '.config', 'claude', 'claude_desktop_config.json');
  }

  // Check if file exists and merge
  let existingConfig: Record<string, unknown> = {};
  if (existsSync(mcpConfigPath)) {
    try {
      existingConfig = JSON.parse(readFileSync(mcpConfigPath, 'utf-8'));
    } catch {
      // Ignore parse errors
    }
  }

  const mcpConfig = generateClaudeDesktopMcpConfig();
  const mergedConfig = {
    ...existingConfig,
    mcpServers: {
      ...(existingConfig.mcpServers as Record<string, unknown> || {}),
      ...mcpConfig.mcpServers,
    },
  };

  // Ensure directory exists
  const dir = dirname(mcpConfigPath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  writeFileSync(mcpConfigPath, JSON.stringify(mergedConfig, null, 2), 'utf-8');
}
