#!/bin/bash

# Known real packages from user
KNOWN_REAL=(
  "@modelcontextprotocol/server-aws-kb-retrieval"
  "@modelcontextprotocol/server-filesystem"
  "@modelcontextprotocol/server-github"
  "@modelcontextprotocol/server-postgres"
  "@modelcontextprotocol/server-sqlite"
  "@modelcontextprotocol/server-brave-search"
  "@modelcontextprotocol/server-puppeteer"
  "@modelcontextprotocol/server-google-drive"
  "@modelcontextprotocol/server-slack"
  "@modelcontextprotocol/server-fetch"
  "@modelcontextprotocol/server-memory"
  "@modelcontextprotocol/server-sequential-thinking"
  "@modelcontextprotocol/server-everything"
  "@modelcontextprotocol/server-playwright"
)

# Packages from configs
PACKAGES=(
  "@modelcontextprotocol/server-airtable"
  "@modelcontextprotocol/server-alchemy"
  "@modelcontextprotocol/server-anthropic"
  "@modelcontextprotocol/server-aws"
  "@modelcontextprotocol/server-aws-bedrock"
  "@modelcontextprotocol/server-azure"
  "@modelcontextprotocol/server-brave-search"
  "@modelcontextprotocol/server-chainstack"
  "@modelcontextprotocol/server-circleci"
  "@modelcontextprotocol/server-cloudflare"
  "@modelcontextprotocol/server-datadog"
  "@modelcontextprotocol/server-discord"
  "@modelcontextprotocol/server-docker"
  "@modelcontextprotocol/server-elasticsearch"
  "@modelcontextprotocol/server-figma"
  "@modelcontextprotocol/server-filesystem"
  "@modelcontextprotocol/server-firecrawl"
  "@modelcontextprotocol/server-gcp"
  "@modelcontextprotocol/server-git"
  "@modelcontextprotocol/server-github"
  "@modelcontextprotocol/server-gitlab"
  "@modelcontextprotocol/server-google-cloud-run"
  "@modelcontextprotocol/server-google-drive"
  "@modelcontextprotocol/server-infura"
  "@modelcontextprotocol/server-jira"
  "@modelcontextprotocol/server-kubernetes"
  "@modelcontextprotocol/server-linear"
  "@modelcontextprotocol/server-mongodb"
  "@modelcontextprotocol/server-netlify"
  "@modelcontextprotocol/server-notion"
  "@modelcontextprotocol/server-openai"
  "@modelcontextprotocol/server-openai-image"
  "@modelcontextprotocol/server-perplexity"
  "@modelcontextprotocol/server-pinecone"
  "@modelcontextprotocol/server-planetscale"
  "@modelcontextprotocol/server-playwright"
  "@modelcontextprotocol/server-postgres"
  "@modelcontextprotocol/server-postgresql"
  "@modelcontextprotocol/server-prisma"
  "@modelcontextprotocol/server-quicknode"
  "@modelcontextprotocol/server-railway"
  "@modelcontextprotocol/server-redis"
  "@modelcontextprotocol/server-sendgrid"
  "@modelcontextprotocol/server-sentry"
  "@modelcontextprotocol/server-slack"
  "@modelcontextprotocol/server-solana-agent-kit"
  "@modelcontextprotocol/server-sqlite"
  "@modelcontextprotocol/server-stripe"
  "@modelcontextprotocol/server-supabase"
  "@modelcontextprotocol/server-tenderly"
  "@modelcontextprotocol/server-thegraph"
  "@modelcontextprotocol/server-twilio"
  "@modelcontextprotocol/server-vercel"
  "@modelcontextprotocol/server-web3-multichain"
)

echo "Checking npm packages..."
echo "========================"
echo ""

for pkg in "${PACKAGES[@]}"; do
  npm view "$pkg" version > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "✅ EXISTS: $pkg"
  else
    echo "❌ NOT FOUND: $pkg"
  fi
done
