#!/usr/bin/env tsx
/**
 * OPUS 67 - Skill Generator
 * Generates all 140 skill .md files from registry.yaml
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { parse as parseYaml } from "yaml";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

// ESM-compatible __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface Skill {
  id: string;
  name: string;
  tier: number;
  token_cost: number;
  type?: string;
  metadata_path?: string;
  capabilities: string[];
  auto_load_when: {
    keywords?: string[];
    file_types?: string[];
    directories?: string[];
  };
  mcp_connections?: string[];
}

interface SkillRegistry {
  meta: {
    version: string;
    total_skills: number;
  };
  skills: Skill[];
  skills_v31?: Skill[];
  skills_v41?: Skill[];
}

/**
 * Generate skill .md file content
 */
function generateSkillMarkdown(skill: Skill): string {
  const mcps = skill.mcp_connections && skill.mcp_connections.length > 0
    ? skill.mcp_connections.join(", ")
    : "None";

  const keywords = skill.auto_load_when?.keywords?.join(", ") || "N/A";
  const fileTypes = skill.auto_load_when?.file_types?.join(", ") || "N/A";
  const directories = skill.auto_load_when?.directories?.join(", ") || "N/A";

  return `# ${skill.name}

> **ID:** \`${skill.id}\`
> **Tier:** ${skill.tier}
> **Token Cost:** ${skill.token_cost}
> **MCP Connections:** ${mcps}

## 🎯 What This Skill Does

${skill.capabilities.map(cap => `- ${cap}`).join("\n")}

## 📚 When to Use

This skill is automatically loaded when:

- **Keywords:** ${keywords}
- **File Types:** ${fileTypes}
- **Directories:** ${directories}

## 🚀 Core Capabilities

${skill.capabilities.map((cap, idx) => `
### ${idx + 1}. ${cap}

[Detailed implementation guidance goes here]

**Best Practices:**
- TODO: Add best practices

**Common Patterns:**
\`\`\`typescript
// TODO: Add code examples
\`\`\`

**Gotchas:**
- TODO: Add common pitfalls to avoid
`).join("\n")}

## 💡 Real-World Examples

### Example 1: TODO Title
\`\`\`typescript
// TODO: Add comprehensive example
\`\`\`

### Example 2: TODO Title
\`\`\`typescript
// TODO: Add comprehensive example
\`\`\`

## 🔗 Related Skills

TODO: List skills that work well with this one

## 📖 Further Reading

TODO: Add links to documentation, tutorials, etc.

---

*This skill is part of OPUS 67 v5.1 - "The Precision Update"*
*Generated by skill-generator.ts - Content to be filled by specialized agents*
`;
}

/**
 * Main generator function
 */
async function generateAllSkills() {
  console.log("🔨 OPUS 67 Skill Generator");
  console.log("=" + "=".repeat(50));

  // Load registry
  const registryPath = join(__dirname, "..", "skills", "registry.yaml");
  const registry: SkillRegistry = parseYaml(readFileSync(registryPath, "utf-8"));

  console.log(`\n📋 Registry loaded: ${registry.meta.total_skills} skills defined`);

  // Output directory
  const outputDir = join(__dirname, "..", "skills", "definitions");
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  let generated = 0;
  let skipped = 0;
  let errors = 0;

  // Collect all skills from all sections
  const allSkills: Skill[] = [
    ...registry.skills,
    ...(registry.skills_v31 || []),
    ...(registry.skills_v41 || [])
  ];

  console.log(`📊 Processing ${allSkills.length} total skills from all sections`);
  console.log(`   - Main skills: ${registry.skills.length}`);
  console.log(`   - v3.1 skills: ${registry.skills_v31?.length || 0}`);
  console.log(`   - v4.1 skills: ${registry.skills_v41?.length || 0}\n`);

  // Process each skill
  for (const skill of allSkills) {
    const outputPath = join(outputDir, `${skill.id}.md`);

    // Skip if already exists
    if (existsSync(outputPath)) {
      console.log(`⏭️  Skipping ${skill.id} (already exists)`);
      skipped++;
      continue;
    }

    try {
      const content = generateSkillMarkdown(skill);
      writeFileSync(outputPath, content, "utf-8");
      console.log(`✅ Generated ${skill.id}`);
      generated++;
    } catch (error) {
      console.error(`❌ Error generating ${skill.id}:`, error);
      errors++;
    }
  }

  console.log("\n" + "=".repeat(50));
  console.log(`✅ Generation complete!`);
  console.log(`   Generated: ${generated} files`);
  console.log(`   Skipped: ${skipped} files (already exist)`);
  console.log(`   Errors: ${errors} files`);
  console.log(`   Total: ${generated + skipped} / ${registry.meta.total_skills}`);

  // Check if document-generation skills exist
  const docGenDir = join(outputDir, "document-generation");
  if (existsSync(docGenDir)) {
    console.log(`\n📁 document-generation/ directory exists with 4 skills`);
  }

  console.log("\n🎯 Next Steps:");
  console.log("   1. Review generated skill templates");
  console.log("   2. Deploy 20 agents to fill out skill content");
  console.log("   3. Test skill loading");
  console.log("   4. Publish OPUS 67 v5.1.1");
}

// Run generator
generateAllSkills().catch((error) => {
  console.error("❌ Fatal error:", error);
  process.exit(1);
});
