# Node.js Backend Expert

> **ID:** `node-backend`
> **Tier:** 3
> **Token Cost:** 8000
> **MCP Connections:** postgres, supabase

## 🎯 What This Skill Does

- Build REST and GraphQL APIs
- Implement middleware patterns
- Handle authentication (JWT, OAuth)
- Configure Express/Fastify/Hono
- Manage async operations

## 📚 When to Use

This skill is automatically loaded when:

- **Keywords:** node, express, fastify, hono, backend, api, middleware, jwt
- **File Types:** .ts, .js
- **Directories:** server/, api/, backend/

## 🚀 Core Capabilities


### 1. Build REST and GraphQL APIs

[Detailed implementation guidance goes here]

**Best Practices:**
- TODO: Add best practices

**Common Patterns:**
```typescript
// TODO: Add code examples
```

**Gotchas:**
- TODO: Add common pitfalls to avoid


### 2. Implement middleware patterns

[Detailed implementation guidance goes here]

**Best Practices:**
- TODO: Add best practices

**Common Patterns:**
```typescript
// TODO: Add code examples
```

**Gotchas:**
- TODO: Add common pitfalls to avoid


### 3. Handle authentication (JWT, OAuth)

[Detailed implementation guidance goes here]

**Best Practices:**
- TODO: Add best practices

**Common Patterns:**
```typescript
// TODO: Add code examples
```

**Gotchas:**
- TODO: Add common pitfalls to avoid


### 4. Configure Express/Fastify/Hono

[Detailed implementation guidance goes here]

**Best Practices:**
- TODO: Add best practices

**Common Patterns:**
```typescript
// TODO: Add code examples
```

**Gotchas:**
- TODO: Add common pitfalls to avoid


### 5. Manage async operations

[Detailed implementation guidance goes here]

**Best Practices:**
- TODO: Add best practices

**Common Patterns:**
```typescript
// TODO: Add code examples
```

**Gotchas:**
- TODO: Add common pitfalls to avoid


## 💡 Real-World Examples

### Example 1: TODO Title
```typescript
// TODO: Add comprehensive example
```

### Example 2: TODO Title
```typescript
// TODO: Add comprehensive example
```

## 🔗 Related Skills

TODO: List skills that work well with this one

## 📖 Further Reading

TODO: Add links to documentation, tutorials, etc.

---

*This skill is part of OPUS 67 v5.1 - "The Precision Update"*
*Generated by skill-generator.ts - Content to be filled by specialized agents*
